config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :news
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    # CrawlerpageJob.perform_later('http://mds.gov.br/area-de-imprensa/noticias')
    # CrawlerpageJob.perform_now('http://mds.gov.br/area-de-imprensa/noticias')
    @total_news = News.count
    @grid = NewsGrid.new(grid_params) do |scope|
      scope.page(params[:page])
    end
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  protected

  def grid_params
    params.fetch(:news_grid, {}).permit!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:source, :url, :title, :subtitle, :publish_data, :collection_date, :body_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crawler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/_breadcrumb-search.html.erb
<nav class="breadcrumb has-succeeds-separator" aria-label="breadcrumbs">
  <ul>
    <li><a href="#">CrawlerGov</a></li>
    <li><a href="#">News</a></li>
    <li class="is-active"><a href="#" aria-current="page">Index</a></li>
  </ul>
</nav>
<span class="tag is-warning is-medium">Total de Dados: <%= @total_news %></span>
<button class="button is-primary is-small" id="show">Search</button>
<button class="button is-primary is-danger" id="hide">Hide</button>
<br/>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :publish_data %>
    <%= form.date_select :publish_data %>
  </div>

  <div class="field">
    <%= form.label :collection_date %>
    <%= form.date_select :collection_date %>
  </div>

  <div class="field">
    <%= form.label :body_text %>
    <%= form.text_field :body_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_loader.html.erb
<div class="columns is-mobile is-centered is-hidden">
  <div class="loadering column is-half">
    <p class="bd-notification is-primary">
      <code class="html">Processando Jobs no Crawler ...</code><br>
    </p>
    <figure class="image is-flex is-justify-content-center">
      <img  src="https://media.giphy.com/media/LeQ4gz6XOhla8/source.gif">
    </figure>
  </div>
</div>

app/views/news/_navbar.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://cdn4.iconfinder.com/data/icons/seo-glyph-style/150/web-crawler-512.png">
      CrawlerGov
    </a>
    <div class="navbar-burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="https://bulma.io/">
        Home
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a class="is-info button" target="_blank" href="https://www.linkedin.com/in/henriqueutsch/">
              <span>
                My Linkedin
              </span>
            </a>
          </p>
          <p class="control">
            <a class="button is-primary" target="_blank" href="https://gitlab.com/henriqueutsch/crawler">
              <span>Project Link</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/news/backupindex.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Url</th>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Publish data</th>
      <th>Collection date</th>
      <th>Body text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.source %></td>
        <td><%= news.url %></td>
        <td><%= news.title %></td>
        <td><%= news.subtitle %></td>
        <td><%= news.publish_data %></td>
        <td><%= news.collection_date %></td>
        <td><%= news.body_text %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New News', new_news_path %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<%= render "navbar" %>
<br/>
<br/>
<div class="columns">
  <div class="column"></div>
  <div class="column is-four-fifths">
    <%= render "breadcrumb-search" %>
    <%= render "loader" %>
    <br>
    <div id="searchbox">
      <%= datagrid_form_for @grid, :method => :get, :url => news_index_path %>
    </div>
    <% if @total_news > 0 %>
      <%= paginate(@grid.assets) %>
      <%= datagrid_table @grid %>
      <%= paginate(@grid.assets) %>
    <% else %>
    <div class="notification is-warning">
      <button class="delete"></button>
      O sistema ainda nao possui dados, inicie a coleta de dados para ver algum resultado.
      Execute: <strong>rake run_crawler:mds</strong>
    </div>
    <% end %>
  </div>
  <div class="column"></div>
</div>


<script>
$(document).ready(function(){
  $("#searchbox").hide();
  $("#hide").hide();
  $("#hide").click(function(){
    $("#searchbox").hide();
    $("#hide").hide();
    $("#show").show();
  });
  $("#show").click(function(){
    $("#searchbox").show();
    $("#show").hide();
    $("#hide").show();
  });
});
</script>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @news.source %>
</p>

<p>
  <strong>Url:</strong>
  <%= @news.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @news.subtitle %>
</p>

<p>
  <strong>Publish data:</strong>
  <%= @news.publish_data %>
</p>

<p>
  <strong>Collection date:</strong>
  <%= @news.collection_date %>
</p>

<p>
  <strong>Body text:</strong>
  <%= @news.body_text %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>